Updating with endpoint for Article ID search, error handling,  and tests
bayardt/be-nc-news pull request #3
Opened 2022-02-14 16:26 UTC by bayardt

2022-02-14 16:48 UTC, daviidbartlett commented on __tests__/endpoints.test.js
> +          expect(body.msg).toBe("No article found for article_id: 10000");
this is not an invalid route

2022-02-14 16:48 UTC, daviidbartlett commented on app.js
> +});
consider breaking this down into separate error handling middleware functions

2022-02-15 12:44 UTC, popatre requested changes

2022-02-15 12:44 UTC, popatre commented on __tests__/endpoints.test.js
> +    test("status: 200 - responds with the specified article.", () => {
Your declaring that you're testing for a specified article, but the test just checks for ANY object that matches those matchers. 

If you're after a specific article, you can out the data you expect to get back from that article. 
At the moment you could be getting the wrong article, and your test wouldnt show this.

2022-02-15 14:51 UTC, popatre approved these changes
Much better - you're actually checking that the correct data is returning now.

2022-02-15 15:06 UTC, merged